apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-29-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-29
      version: green
  template:
    metadata:
      labels:
        app: project-29
        version: green
    spec:
      containers:
        - name: project-29
          image: project-29-green:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
