apiVersion: v1
kind: Pod
metadata:
  name: project-43-app
spec:
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "echo 'Project 43 persistent data' > /data/message.txt && cat /data/message.txt && sleep 3600"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: project-43-pvc
