name: CI Environment Varibales

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  environment-test:
    runs-on: ubuntu-latest
  
    env:
      APP_NAME: DevOps-CI-App
      APP_ENV: testing
      DEMO_SECRET: ${{ secrets.DEMO_SECRET}}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Display CI Environment
        run: bash Day-03-CI-CD/Project-23/app.sh
        
      - name: Test secret masking
        run: echo "Secret value: $DEMO_SECRET"

      - name: Verify Secret is available
        run: |
          if [ -n "$DEMO_SECRET" ]; then
            echo "Secret is available to the CI job"
          else 
            echo "Secret is missing"
            exit 1
          fi 
